name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Clone other project
        run: |
          git clone https://github.com/bondarenkokate73/simbirsoft_sdet_project.git

      - name: Set up Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version

      - name: Start services with Docker Compose
        run: |
            docker-compose -f simbirsoft_sdet_project/docker-compose.yml up -d

      - name: Install dependencies
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Stop services with Docker Compose
        if: always()
        run: |
            docker-compose -f simbirsoft_sdet_project/docker-compose.yml down
